"""Common Japanese surnames with romaji readings.

Used by the LLM translator to detect person names in ASR output and
provide romaji equivalents so the translation model does not hallucinate
literal kanji meanings (e.g. 中野 "middle field" → "giữa đồng").

Detection set entries are pure kanji strings searched via `in` operator
(no re module needed). Romaji entries use Hepburn romanization without
macrons (Tokyo → Tokyo, not Tōkyō) for maximum NLLB/LLM copy-through.
"""

from __future__ import annotations

SURNAME_MAP: dict[str, str] = {
    # ── Top 50 most common Japanese surnames ──
    "佐藤": "Sato",
    "鈴木": "Suzuki",
    "高橋": "Takahashi",
    "田中": "Tanaka",
    "渡辺": "Watanabe",
    "渡邊": "Watanabe",
    "伊藤": "Ito",
    "山本": "Yamamoto",
    "中村": "Nakamura",
    "小林": "Kobayashi",
    "加藤": "Kato",
    "吉田": "Yoshida",
    "山田": "Yamada",
    "佐々木": "Sasaki",
    "井上": "Inoue",
    "木村": "Kimura",
    "林": "Hayashi",
    "斎藤": "Saito",
    "斉藤": "Saito",
    "清水": "Shimizu",
    "山口": "Yamaguchi",
    "松本": "Matsumoto",
    "石井": "Ishii",
    "松井": "Matsui",
    "阿部": "Abe",
    "森": "Mori",
    "池田": "Ikeda",
    "橋本": "Hashimoto",
    "石川": "Ishikawa",
    "山崎": "Yamazaki",
    "山﨑": "Yamazaki",
    "小川": "Ogawa",
    "藤田": "Fujita",
    "後藤": "Goto",
    "岡田": "Okada",
    "長谷川": "Hasegawa",
    "村上": "Murakami",
    "近藤": "Kondo",
    "中川": "Nakagawa",
    "前田": "Maeda",
    "藤原": "Fujiwara",
    "上田": "Ueda",
    "西村": "Nishimura",
    "福田": "Fukuda",
    "大野": "Ono",
    "太田": "Ota",
    "杉山": "Sugiyama",
    "金子": "Kaneko",
    "栗原": "Kurihara",
    "吉村": "Yoshimura",
    "横山": "Yokoyama",
    "川村": "Kawamura",
    "平野": "Hirano",
    "片山": "Katayama",
    "三浦": "Miura",
    "川上": "Kawakami",
    "河野": "Kono",
    "永井": "Nagai",
    "岡本": "Okamoto",
    "大塚": "Otsuka",
    "田口": "Taguchi",
    "小山": "Koyama",
    "安藤": "Ando",
    "野口": "Noguchi",
    "古賀": "Koga",
    "松田": "Matsuda",
    "中山": "Nakayama",
    "菊池": "Kikuchi",
    "原田": "Harada",
    "工藤": "Kudo",
    "五十嵐": "Igarashi",
    "石田": "Ishida",
    "小島": "Kojima",
    "内田": "Uchida",
    "川口": "Kawaguchi",
    "上野": "Ueno",
    "広瀬": "Hirose",
    "今井": "Imai",
    "大島": "Oshima",
    "沢田": "Sawada",
    "澤田": "Sawada",
    "竹内": "Takeuchi",
    "増田": "Masuda",
    "中島": "Nakajima",
    "吉岡": "Yoshioka",
    "西川": "Nishikawa",
    "久保": "Kubo",
    "関": "Seki",
    "松浦": "Matsuura",
    "岡崎": "Okazaki",
    "野村": "Nomura",
    "丹羽": "Niwa",
    "坂本": "Sakamoto",
    "高田": "Takada",
    "塚本": "Tsukamoto",
    "小野": "Ono",
    "篠原": "Shinohara",
    "武田": "Takeda",
    "水野": "Mizuno",
    "川崎": "Kawasaki",
    "榎本": "Enomoto",
    # ── Names from evidence logs ──
    "中野": "Nakano",
    "羽根": "Hane",
    "深瀬": "Fukase",
    "大森": "Omori",
}

SURNAME_SET: frozenset[str] = frozenset(SURNAME_MAP.keys())
